# Generated by Django 2.0.1 on 2018-01-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_answer', models.CharField(max_length=100, verbose_name='Posible Respuesta')),
                ('right_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total de preguntas')),
                ('total_right_answers', models.PositiveIntegerField(default=0, verbose_name='Respuestas Correctas')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='%')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_given', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
        ),
    ]
