# Generated by Django 2.0.1 on 2018-01-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Promedio'),
        ),
    ]
